# -*- coding: utf-8 -*-
"""CakePool.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LeFMfBac2uzTuPdR9h7ML7LuIHc-g9rQ
"""

import matplotlib.pyplot as plt
import numpy as np

cakes = 6.169
APR = 89.15
comisionBNB = 0.0016
CAKEBNB = 0.05517

comisionCAKE = comisionBNB/CAKEBNB
print(comisionCAKE)

def buscarMejorInversion(diasEspera, inversion, comision, rendimiento):
    totalDias = 365
    espacioDias = 0
    gananciaDiaria = 0
    for x in range(totalDias):
        gananciaDiaria += inversion*rendimiento/(100*totalDias)
        espacioDias += 1
        if espacioDias >= diasEspera:
            espacioDias = 0
            inversion += (gananciaDiaria - comision)
            gananciaDiaria = 0
    return inversion + gananciaDiaria

ganancias = []
for x in range(1,25,1):
    ganancias.append(buscarMejorInversion(x, cakes, comisionCAKE, APR))

x = np.linspace(1,len(ganancias),len(ganancias))

print(np.shape(x))
print(np.shape(ganancias))
print(x)

fig, axs = plt.subplots(figsize=(5, 5))
axs.plot(x, ganancias, marker='o', markersize=5)
axs.set_ylabel("Cake Earned", fontsize=12)
axs.set_xlabel('Intervalo Dias')
plt.grid(True)
plt.show()

